version: '2'
services:
  meta-api:
    build: .
    image: maayanlab/signature-commons-metadata-api-many:1.12.7
    env_file: .env
  meta-db:
    build: ./docker/postgres
    image: meta-db
    env_file: .env
    environment:
      - POSTGRES_DB
      - POSTGRES_TEST_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5433:5432
    volumes:
      - signature-commons-metadata-api-metadata-db:/var/lib/postgresql/data
volumes:
  signature-commons-metadata-api-metadata-db:
